### ISSUE TITLE
Not an editor command

### ISSUE THREAD

**Issue by codeinabox** [junegunn/vim-emoji#11]
I can't get this to work in Neovim 0.1.2 or Vim 7.4, get the following error

> E492: Not an editor command: emoji#available()

**Comment by junegunn** [comment]
What exactly did you do?

**Comment by codeinabox** [comment]
I just did `emoji#available()`. Plugin was installed with Vundle fine, can see it in bundles directory

**Comment by junegunn** [comment]
That is not a proper Vimscript expression. Try with echo or call.

**Comment by codeinabox** [comment]
Thank you for the quick reply, that worked perfect

**Comment by codeinabox** [comment]
Though I am still having issues getting it to work. Getting the following error

> 
> Error detected while processing /Users/matt/.vimrc:
> E117: Unknown function: emoji#available
> E15: Invalid expression: emoji#available()

The .vimrc in question is 

```vim
	if emoji#available()
		let g:gitgutter_sign_added = emoji#for('small_blue_diamond')
		let g:gitgutter_sign_modified = emoji#for('small_orange_diamond')
		let g:gitgutter_sign_removed = emoji#for('small_red_triangle')
		let g:gitgutter_sign_modified_removed = emoji#for('collision')
	endif
	" }}}
```

**Comment by junegunn** [comment]
Cannot reproduce. Please provide a minimal vimrc (less than 10 lines) I can use to reproduce the problem.

**Comment by codeinabox** [comment]
Moving that block to the bottom of my .vimrc fixes everything but if I insert it at [line 35 of my current .vimrc](https://github.com/codeinabox/dotfiles/blob/f800d26f5505b2970e6f858747156a5d26237812/.vimrc#L35)

Is there something else that needs to be called before before I can call `emoji#available()`

**Comment by junegunn** [comment]
Yes, plugins are not available before `vundle#end()`.
