### ISSUE TITLE
Why only OS X support?

### ISSUE THREAD

**Issue by nfischer** [junegunn/vim-emoji#12]
Just tried this on my Ubuntu 15.10 system (I overrode the OS-check to always set `s:available` to 1), and emojis seem to work fine for me. I've tried this out on...

 - gvim
 - terminal vim
 - nvim

I've attached a screenshot of my output from running `:echo emoji#for('fishing_pole_and_fish') . emoji#for('smiley')` (look in the bottom left corner of the screenshot).

![screenshot from 2016-04-27 00-14-46](https://cloud.githubusercontent.com/assets/5801521/14844587/37c913d6-0c0d-11e6-9834-d3dfbe2da161.png)

I don't think I installed any extra fonts in order to do this.

**Comment by wladston** [comment]
Can your operating system display emoji correctly in any other application? (Such as in a GUI text editor).

**Comment by nfischer** [comment]
It displays about the same in gedit as it does in vim. Is this an "incorrect" rendering of the emoji? It just seems like it's a different rendering than iOS/Android might do, not necessarily "incorrect." Although please let me know if I'm mistaken.

**Comment by nfischer** [comment]
Also, thanks for the quick response!

**Comment by wladston** [comment]
Yeah, basically this plugin's function is to help you insert emojis in your text by using their names, instead of their unicode values. From what you said, it looks like the plugin seems to be working correctly. What kind of behaviour were you expecting to see?

**Comment by nfischer** [comment]
The plugin does not work as expected, unless I modify it. By default, it refuses to work on Linux. To get the behavior I showed, I had to manually edit the code where it says "if this is not named Darwin, refuse to function." I'll send over a PR so the diff is clear.

**Comment by junegunn** [comment]
Yeah I had the wrong impression that Emojis were proprietary to Apple, but it's not true. Will change that.

**Comment by nfischer** [comment]
@junegunn Thanks! Works as expected now.
