### ISSUE TITLE
deoplete support

### ISSUE THREAD

**Issue by gilligan** [junegunn/vim-emoji#13]
It would be great if you could add support for deoplete - making vim-emoji available as deoplete input source. 

One example is [neco-look](https://github.com/ujihisa/neco-look/blob/master/rplugin/python3/deoplete/sources/look.py) that does that for example. Info is also available in the [deoplete documentation](https://github.com/Shougo/deoplete.nvim/blob/master/doc/deoplete.txt).

I would have loved to provide it myself but I suck at viml *and* python ;)

**Comment by junegunn** [comment]
Thanks for the suggestion, but I don't use the plugin and I don't prefer introducing external dependencies to my plugins. The raw emoji data can be retrieved using `emoji#data#dict()`, so it should be easy to build something out of it.

**Comment by blueyed** [comment]
@gilligan

Have you (or someone else subscribed here) looked into this already?

:flower_playing_cards:

**Comment by fszymanski** [comment]
If anyone is still interested, check out [deoplete-emoji](https://github.com/fszymanski/deoplete-emoji). I did not spend much time on it (it's a work in progress).
