### ISSUE TITLE
Visual gap on the suggestion list

### ISSUE THREAD

**Issue by rafaelrinaldi** [junegunn/vim-emoji#14]
![screen shot 2016-05-12 at 2 50 27 pm](https://cloud.githubusercontent.com/assets/87162/15226552/2c7dc17a-1851-11e6-94a0-df3c3c7576d4.png)

Any idea why this is happening? Maybe it's a font issue? I use [PragmataPro](http://www.fsd.it/shop/fonts/pragmatapro/) but tried Menlo and Monaco too, and experienced the same issue.

**Comment by junegunn** [comment]
I'm also seeing the issue for quite some time. I remember it was since I upgraded Vim one day. Haven't had time to dig into it.

**Comment by rafaelrinaldi** [comment]
@junegunn Alright, thanks for the feedback. It doesn't seem to be related to the plugin itself so I'm going to close the issue.

Cheers.

**Comment by wladston** [comment]
Just as an observation, it seems like this issue is related to the fact that Emojis generally occupy more than the width of one monospaced char. It would be interesting if there was a way to instruct vim to use two unicode characters to render emojis. That should probably be possible, and it would fix this issue and many others as well.

**Comment by rafaelrinaldi** [comment]
@wladston Yeah, what bothers me is that it used to work properly until few weeks ago. Something regarding font rendering changed on either Vim or iTerm.

**Comment by junegunn** [comment]
@rafaelrinaldi I believe it's Vim. They look fine on system default Vim (`/usr/bin/vim`).

**Comment by rpereira** [comment]
I have added emojis to my statusline and I do have the same issue. For instance, when I change to another buffer.

![screen shot 2016-11-13 at 12 58 00 pm](https://cloud.githubusercontent.com/assets/3859158/20245812/dfc9fe16-a9a0-11e6-98a9-13988dd7046a.png)

The current buffer is the one on the right.
