### ISSUE TITLE
Emoji without colors

### ISSUE THREAD

**Issue by caneta** [junegunn/vim-emoji#16]
Hi @junegunn.
I cannot get the emoji colored as in your scrrenshots, instead I get the following:
![vim-emoji](https://cloud.githubusercontent.com/assets/4066659/17129690/e371522c-5314-11e6-9877-89f7168a1970.png)
I'm using neovim-0.1.5-dev on an Ubuntu 12.04.
I use [Oceanic Next](https://github.com/mhartington/oceanic-next) as colorscheme, but nothing changes if I use another one.
So, what is getting wrong?

**Comment by junegunn** [comment]
The screenshots were taken on OS X and probably Linux desktop environment displays the characters differently. I don't use LInux desktop so I don't think I can be of help. You might want to check out the following links:
- #12
- http://askubuntu.com/questions/639552/how-to-get-apple-color-emojis-to-work-on-ubuntu

**Comment by caneta** [comment]
Ok thanks, so I'll wait for Linux to support it.

**Comment by caneta** [comment]
In August 2017, [Cairo library](https://cairographics.org/) introduced [colored emoji support](https://www.phoronix.com/scan.php?page=news_item&px=Cairo-1.15.8-Colored-Emoji): [the wait is over](https://superuser.com/questions/1122326/is-there-a-way-to-get-colored-emoji-in-any-terminal-emulator-on-linux/1252046#1252046)!

![vimemojilinux](https://user-images.githubusercontent.com/4066659/45239757-a5e0de80-b2e6-11e8-924e-4fcfe71eb250.png)
