### ISSUE TITLE
Install with pathogen?

### ISSUE THREAD

**Issue by searls** [junegunn/vim-emoji#17]
Would it be trivial to make this installable via [pathogen](https://github.com/tpope/vim-pathogen)?

```
cd ~/.vim/bundle
git clone git://github.com/junegunn/vim-emoji.git
```

Would be nice in case we don't otherwise use Plug

**Comment by junegunn** [comment]
It already works with pathogen. All major Vim plugin managers, vim-plug, vundle, neobundle, etc, are compatible to pathogen.

**Comment by searls** [comment]
Bummer. It didn't seem to work for me then. I'll investigate when I'm back at my machine

**Comment by TimDaub** [comment]
Any update on this?
