### ISSUE TITLE
Rendering issues in Neovim

### ISSUE THREAD

**Issue by codeinabox** [junegunn/vim-emoji#18]
I've noticed that since version 0.1.5 of Neovim there has been rendering issues with emoji. Below is how it appears, which may be due to https://github.com/neovim/neovim/issues/5149

![neovim](https://cloud.githubusercontent.com/assets/2069958/18291342/34c361de-747f-11e6-8d2f-80a0e98cd3f0.png)

Yet in Vim with the same configuration renders without issue

![vim](https://cloud.githubusercontent.com/assets/2069958/18291354/40742202-747f-11e6-9f38-042d9b823e18.png)

**Comment by gaugau** [comment]
<img width="481" alt="screen shot 2016-09-09 at 1 19 37 pm" src="https://cloud.githubusercontent.com/assets/6811530/18377258/3182777c-7690-11e6-9240-1ae8f850a2f8.png">
<img width="1303" alt="screen shot 2016-09-09 at 1 19 59 pm" src="https://cloud.githubusercontent.com/assets/6811530/18377259/31b27b34-7690-11e6-9f1c-5ff7024317e2.png">

It happens for me as well. Nvim 0.1.5 on ITerm2 v3.0.8 Mac OSX El Capitan

**Comment by modille** [comment]
FYI, a Neovim fix got merged as of  https://github.com/neovim/neovim/commit/f610b807b48dbaf96fe05459927a8c926b67f8bb

It didn't make it into 0.1.6, but if you reinstall from HEAD or wait for the next release then this issue should go away.

**Comment by gianpieroc** [comment]
I'm using master branch of neovim and still having the same issue :( 
Help Please
