### ISSUE TITLE
`emoji#for` appends whitespace

### ISSUE THREAD

**Issue by alxndr** [junegunn/vim-emoji#3]
Thanks for making this plugin, and providing the [example usage]() with a `:s` command!

I've noticed that if the emoji name comes last on the line of text, the replacement adds a space character to the end of the line. It seems like `emoji#for(...)` is [designed to insert a space after the emoji when there are more characters following](https://github.com/junegunn/vim-emoji/blob/b4823f4e57e29/test/emoji.vader#L33-L35), but should it do that when the emoji should be the last thing on the line?

**Comment by junegunn** [comment]
> It seems like emoji#for(...) is designed to insert a space after the emoji when there are more characters following

No `emoji#for` is just a pure function that does not know the context of the call. It simply appends a space if the optional `pad` argument is set.

https://github.com/junegunn/vim-emoji#list-of-functions

So, you'll have to write your own commands or vimscript to handle that. The most simple way to do it is to remove trailing whitespaces afterwards.

```vim
:%s/:\([^:]\+\):/\=emoji#for(submatch(1), submatch(0))/g | %s/ *$//
```

Or we can the pad argument depending on the column of the occurrence

```vim
:%s/:\([^:]\+\):/\=emoji#for(submatch(1), submatch(0), col('.') + len(submatch(0)) == col('$') - 1)/g
```

**Comment by alxndr** [comment]
Aha, so I can just modify the call to `emoji#for` so [it does not insert the padding at all](https://github.com/alxndr/dotfiles/blob/4cc9155d/.nvimrc#L144).

Thanks!
