### ISSUE TITLE
Having some issues with padding

### ISSUE THREAD

**Issue by BrandonMathis** [junegunn/vim-emoji#7]
Hey @junegunn love the plugin!

I am having some issues with padding though. The following command returns a 🌸but part of the emoji is being cut off so I want to adjust the padding a bit (I think). 

```
emoji#for('cherry_blossom', ' ', 4)
```

However, I notice no difference when I use that ^ function :(

**Comment by junegunn** [comment]
Actually, the type of the last optional parameter was boolean, 0 or other "truethy" values. I updated the code so that you can pass the size of the desired padding.

**Comment by BrandonMathis** [comment]
excellent! thx @junegunn :dancer:
